name: Build CodePush

on:
  push:
    tags:
      - 'v*.*.*-cp-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Env: set package version"
      run: >
        echo "VERSION=$(cat package.json | grep version | head -1 | awk
        -F: '{ print $2 }' | sed 's/[",\t ]//g')" >> $GITHUB_ENV
    - name: "Env: setup DEV environment"
      if: ${{ startsWith(github.ref, 'refs/tags') && endsWith(github.ref, '-dev') }}
      env:
        ENVFILE: ${{secrets.ENVFILE_DEV}}
      run: echo "$ENV_FILE" > .env
    - name: "Env: setup PRD environment"
      if: ${{ startsWith(github.ref, 'refs/tags') && endsWith(github.ref, '-prd') }}
      env:
        ENV_FILE: ${{secrets.ENVFILE_PRD}}
      run: echo "$ENV_FILE" > .env
    - name: "Env: output .env file to env"
      run: cat .env >> $GITHUB_ENV
    - name: 'Yarn: install'
      run: yarn install
    - name: 'CodePush: deploy iOS app'
      env:
        CODEPUSH_TOKEN: ${{secrets.CODEPUSH_TOKEN}}
      run: |
        npx appcenter-cli codepush release-react \
          --quiet \
          --plist-file "./ios/KremenTransport/Info.plist" \
          --app $CODEPUSH_APP_IOS \
          --token $CODEPUSH_TOKEN \
          --deployment-name $CODEPUSH_DEPLOYMENT \
          --target-binary-version "$CODEPUSH_TARGET_VERSION" \
          --output-dir build/ios \
          --description "$CODEPUSH_RELEASE_NOTE" \
          $CODEPUSH_OPTIONS
    - name: 'CodePush: deploy Android app'
      env:
        CODEPUSH_TOKEN: ${{secrets.CODEPUSH_TOKEN}}
      run: |
        npx appcenter-cli codepush release-react \
          --quiet \
          --app $CODEPUSH_APP_AND \
          --token $CODEPUSH_TOKEN \
          --deployment-name $CODEPUSH_DEPLOYMENT \
          --target-binary-version "$CODEPUSH_TARGET_VERSION" \
          --output-dir build/and \
          --description "$CODEPUSH_RELEASE_NOTE" \
          $CODEPUSH_OPTIONS
